### ISSUE TITLE
New VPC Deploy all defaults/london data, workflow job transform_raw_to_clean-us-east-1 dies

### ISSUE THREAD

**Issue by kpapagno** [aws-quickstart/quickstart-aws-utility-meter-data-analytics-platform#10]
Hi - Thanks for doing this Utility focused quick start!   I decided to give it a try as I'm involved with MDM.  In deploying the quick start, making sure to point out the password requirements for redshift would have been helpful.  2x failed deploys before I thought of choosing a password with upper,lower, and special characters.

I've deployed in a new VPC, with all defaults.

Once triggering the workflow, It gets as far as the **transform_raw_to_clean-us-east-1** job, which dies with a TypeError: sequence item 0: expected str instance, NoneType found.  Looking at the jobs "Error Logs", gives no useful clue as to the error.  The "Logs" is full of output, though the only error i see is 

20/10/28 23:20:58 WARN YarnClient: The GET request failed for the URL http://0.0.0.0:8088/ws/v1/cluster/apps/application_1603926903796_0001 
com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.conn.HttpHostConnectException: Connect to 0.0.0.0:8088 [/0.0.0.0] failed: Connection refused (Connection refused)

The IP address of 0.0.0.0 on port 8088 looks strange to me.    Any suggestions where to look to resolve the issue?
Thanks

Ken

**Comment by sj5n** [comment]
Hi Ken,

thanks for your comment and the hint, we will include this in the parameter description.

To your second point. I suppose you try to work with the London demo data set? For using set you need to set the 'LandingzoneTransformer' parameter during the deployment to 'London'. This will then install the correct parser for the demo data set.

https://aws-quickstart.github.io/quickstart-aws-utility-meter-data-analytics-platform/#_download_sample_demo_dataset

Let me know if this do not solve the issue.

Best
Sascha

**Comment by kpapagno** [comment]
FYI - That was exactly what it was.  Thanks!
