### ISSUE TITLE
It's too easy to mis-configure the required parameters

### ISSUE THREAD

**Issue by stephenhibbert** [aws-quickstart/quickstart-aws-utility-meter-data-analytics-platform#13]
**Step 4 of Launch the Quick Start**

"On the Specify stack details page, change the stack name if needed. Review the parameters for the template. Provide values for the parameters that require input. For all other parameters, review the default settings and customize them as necessary. For details on each parameter, see the Parameter reference section of this guide."

There are 4 'gotchas' we tripped up on that are only revealed when deploying once, see it fail and rollback then configuring the rollback options then deploying again and finally seeing the error. Suggest adding validation earlier to the CFN template and making the documentation clearer which options are required.

The 'london' transformer is not documented clearly in the quick-start, we only found that by tracking down the github issue.
 
Parameter label (name) | Default value | Description
-- | -- | --
Master user name (MasterUsername) | Requires input | Master user name for the Amazon Redshift cluster. The user name must be lowercase, begin with a letter, contain only alphanumeric characters, '_', '+', '.', '@', or '-', and be less than 128 characters.
Master user password (MasterUserPassword) | Requires input | Master user password for the Amazon Redshift cluster. The password must be 8 - 64 characters, contain at least one uppercase letter, at least one lowercase letter, and at least one number. It can only contain ASCII characters (ASCII codes 33-126), except ' (single quotation mark), " (double quotation mark), /, \, or @.
Availability Zones (AvailabilityZones) | Requires input | List of Availability Zones to use for the subnets in the VPC. The logical order is preserved. You must provide two zones, according to AWS best practices. If a third Availability Zone parameter is specified, you must also provide that zone.
Transformer that reads the landing-zone data (LandingzoneTransformer) | london | Defines the transformer for the input data in the landing zone.

**Comment by sj5n** [comment]
- updated documentation
- make london LandingzoneTransformer as default
- add AllowedPattern to parameter fields
