### ISSUE TITLE
Steps to retrain the model not complete

### ISSUE THREAD

**Issue by stephenhibbert** [aws-quickstart/quickstart-aws-utility-meter-data-analytics-platform#15]
We found that retraining the model required the following steps. The JSON provided in the quick start was not complete:

1. When you retrain the model, do the following:
2. Open Step Functions → State Machines → InitialTrainingStateMachine (click)
3. Click Start Execution and paste in the following into the input - change the ML ModelName and ML_Endpoint_name to match the ML Model name. Also provide a unique Training_job_name e.g. training-job-nick-0001 (if you need to run the job again, you must increment the number to make it unique)

{
"ModelName": "ml-model-fafa9336-6f1d-4fa4-bbfe-331afa384dc4",
"ML_endpoint_name": "ml-endpoint-a2544bb9-4d4d-4fd8-bed5-81eab8b0cf31",
"Training_job_name": "training-job-nick-0001",
"Data_start": "2013-01-01",
"Data_end": "2013-10-01",
"Meter_start": 1,
"Training_samples": 50,
"Forecast_period": 7,
"Endpoint_instance_type": "ml.m5.xlarge",
"Training_instance_type": "ml.c5.2xlarge",
"Meter_end": 100,
"Batch_size": 25
}

**Comment by sj5n** [comment]
Doc and process was updated.
