### ISSUE TITLE
Issue in workflow

### ISSUE THREAD

**Issue by kukpkm** [aws-quickstart/quickstart-aws-utility-meter-data-analytics-platform#2]
I get below error in the workflow. ETL glue job shows below type error in raw to clean data transform.
distinctDatesStrList = ','.join(value['date_str'] for value in distinctDates)
typeError: sequence item 0: expected str instance, NoneType found

Before I do anything from my side wanted to check if this is normal.

**Comment by sj5n** [comment]
Hi, it seems, that the date parser can't process your reading date. 
Can you check your input format, and see if the reading date follows the expected format? You can either adjust your input file, or the initial ETL script.

**Comment by kukpkm** [comment]
I use the same sample data as suggested in the quick start guide. So not sure if something wrong with the input file. However, I will check if I can adjust the initial ETL script.

**Comment by sj5n** [comment]
Have you:

- downloaded the London Meter dataset from the provided [Link](https://data.london.gov.uk/download/smartmeter-energy-use-data-in-london-households/3527bf39-d93e-4071-8451-df2ade1ea4f2/Power-Networks-LCL-June2015(withAcornGps).zip)?

- applied the CloudFormation Template with the **LandingzoneTransformer** parameter set to 'london'?

- copied, the **extracted** dataset to the landingzone bucket?

With that the ETL jobs should work OOTB.

**Comment by kukpkm** [comment]
I did the same except I don't see deployment guideline refres the 2nd point anywhere. Where it was mentioned to set the LandingzoneTransformer parameter set to 'london'?

**Comment by sj5n** [comment]
This is indeed missing. To give you some background on this: The **LandingzoneTransformer** defines which code should be loaded to transform the input files from the landingzone to the internal schema. The parameter makes it easy to exchange the inital ETL Jobs. For the London demo data you need a matching transformer which can be activated by setting this value.

Thanks for bringing this topic up. I'll will fix this in the documentation.

**Comment by kukpkm** [comment]
Thank you for the information.  I am not sure if I can do something at the moment to fix this.

**Comment by sj5n** [comment]
You can either redeploy the Quick Start with the different LandingzoneTransformer or rewire the first job in the Glue workflow to 'transform_raw_to_clean_london.py".

**Comment by kukpkm** [comment]
Thank you for your quick help. Surprisingly I could not find this London script in my glue job list. However, I have taken the script from git and able to run the workflow.

**Comment by sshvans** [comment]
Seems like this issue has been addressed. Feel free to reopen it if that's not the case.
