### ISSUE TITLE
VPC Fails to create with when creating stack in cloud formation

### ISSUE THREAD

**Issue by AdrianoNicolucci** [aws-quickstart/quickstart-aws-utility-meter-data-analytics-platform#32]
I attempted to use the cf template to "Deploy Utility Meter Data Analytics into a new VPC on AWS" and the stack fails to create on the VPC. On the Logical ID of "VPC" I am getting a "S3 Error Access Denied" but unfortunately, no more information is provided in the log than that. the role has Admin Access should I would assume S3 Access Denied should not be a problem. Any suggestions for debugging this would be great. 

![image](https://user-images.githubusercontent.com/33879968/125834983-00b6d315-fe0c-4c36-8491-fa9c1eaa1b32.png)

**Comment by sj5n** [comment]
Hi Adriano,
for further debugging you can switch into the resource tap and open the VPC stack, which should give you more detailed information.

One thought on the error itself: Have you changed the region where the Quick Start should be deployed to? If yes, you have also to adjust the "Quick Start S3 bucket Region" parameter on the template configuration page to the region you want to deploy to.

**Comment by AdrianoNicolucci** [comment]
Sure, so see image below for resource tab, unfortunately it does not provide any additional information other than "S3 Error". Yes, I have changed the region where the Quick Start should be deployed to, however, I did adjust the "Quick Start S3 bucket Region" to be the same region. 

![image](https://user-images.githubusercontent.com/33879968/125955763-8fb0a16e-fb02-4f50-b7d3-d6ba52baf681.png)

**Comment by sj5n** [comment]
Hi, couldn't reproduce yet. I'm working on a solution.

**Comment by AdrianoNicolucci** [comment]
Ok I think I identified the root problem of this particular error after trying all possible combinations in the parameters of this template:
I changed the Quick Start S3 bucket name to be a bucket that I created myself. However when I leave it to the default, this error doesn't happen. Shouldn't it be possible to change the name of this bucket or should it be left to be "aws-quickstart"?

**Comment by sj5n** [comment]
Right, that makes sense. This parameter defines the name of the S3 bucket in which the Quick Start content/artifacts lives. 
You only need to change it, if you upload the scripts to a bucket in your own account, this then needs to be referenced here.
