### ISSUE TITLE
London sample meter data is no longer available to download

### ISSUE THREAD

**Issue by AdrianoNicolucci** [aws-quickstart/quickstart-aws-utility-meter-data-analytics-platform#33]
The dataset mentioned for this implementation is currently not available for download. Is there an alternative source available to download this dataset? The instructions also don't mention the schema of this specific sample dataset so I'm not sure what I'm looking for on other websites. 

![image](https://user-images.githubusercontent.com/33879968/125964840-1a61b6ae-c17a-42ed-922a-f47c23ae4654.png)

**Comment by sj5n** [comment]
Hi Adriana, the first link is under maintenance, and will work again in the next weeks. You can download the hafhourly data set from kaggle (mirror link) - registration needed.

**Comment by AdrianoNicolucci** [comment]
Thanks for providing an alternative dataset to use in the meantime while the other dataset is under maintenance. 

Are you aware of any schema changes that have to be made in one or multiple scripts to get the data pipeline to work with this alternative dataset? 

In the "transform_raw_to_clean" aws glue script, I updated the "applymapping" function to rename the columns, included these particular columns of "lclid", "tstp", "energy(kwh/hh)" but the glue job still failed so wondering what else I might be missing. 

Thanks!

**Comment by sj5n** [comment]
The mirror data has a slightly different schema. If you use the latest version (main branch), than the "transform_raw_to_clean" job is able to handle the schema difference, you can find the code in line L96f. 

A previous version of this job was working with hard coded field names, that have been removed recently.

**Comment by AdrianoNicolucci** [comment]
strange so running I was using the latest code, (even uploaded from this git repo directly into aws glue to be sure) when using the "halfhour" dataset which has the following schema: "LCLid", "tstp", "engergy(KWh/hh)" 

I got the following error:

`TypeError: 'StructType' object is not callable` ...Unfortunately the logs don't seem to provide additional useful information to pinpoint what is causing this particular error message.

**Comment by sj5n** [comment]
Make sure to use [this](https://github.com/aws-quickstart/quickstart-aws-utility-meter-data-analytics-platform/blob/develop/assets/glue/scripts/transform_raw_to_clean_london.py) script. That should be copied to 'transform_raw_to_clean.py'. Let me check if something in the master branch is not up to date.

**Comment by AdrianoNicolucci** [comment]
Thanks that seemed to do the trick! thank you for your help
