### ISSUE TITLE
Unable to deploy MDA quickstart v2 due to S3 errors

### ISSUE THREAD

**Issue by awsmrud** [aws-quickstart/quickstart-aws-utility-meter-data-analytics-platform#58]
Deploying the MDA v2 stack results in rollback due to multiple S3 errors:

DataStorageStack: S3 error: The specified key does not exist. For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

IntegrationStack: S3 error: The specified key does not exist.

CopyGlueScriptsStack: S3 error: The specified key does not exist. 

Above errors for both MeterDataGenerator parameter 'Disabled' and 'Enabled' options.

Please advise on resolution.

**Comment by tbulding** [comment]
@awsmrud this issue was opened under the wrong repository it should exist here... https://github.com/aws-quickstart/quickstart-aws-utility-meter-data-analytics-platform-v2
The issue has been resolved. please try again.
